dir:
  img_dir: "/workspace/data/hmi_jpgs_512"

train:
  model: "Alexnet"
  train_set: ["1", "2"]
  cal_set: 3
  test_set: 4
  file_tag: "CP"

optimize:
  epochs: 50
  batch_size: 16
  lr: 0.00001
  max_lr: 0.001
  div_factor: 100000
  wt_decay: [0, 0.01, 0.001, 0.0001]
