train:
  train_set: [1, 2]
  test_set: 4
  data_dir: "/workspace/data/hmi_jpgs_512"
  file_tag: "CP"

optimize:
  epochs: 15
  batch_size: 64
  lr: 1e-5
  max_lr: 1e-3
  wt_decay: [0, 1e-2, 1e-3, 1e-4]
  class_wt: [1, 3, 6]

model:
  models: "Alexnet"