dir:
  img_dir: "/workspace/data/hmi_jpgs_512"

train:
  model: "Alexnet"
  train_set: [1, 2, 3]
  test_set: 4
  file_tag: "MCD"

optimize:
  epochs: 50
  batch_size: 64
  lr: 0.00001
  max_lr: 0.001
  wt_decay: [0, 0.01, 0.001, 0.0001]
